config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'tickets#index'

  resources :tickets, only: %i[show]

  namespace :api do
    namespace :v1 do
      resources :tickets, only: %i[create]
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/excavator.rb
# frozen_string_literal: true

class Excavator < ApplicationRecord
  belongs_to :ticket

  validates :ticket, :company_name, :address, presence: true
end

app/models/ticket.rb
# frozen_string_literal: true

class Ticket < ApplicationRecord
  has_one :excavator, dependent: :destroy

  validates :request_number, :sequence_number, presence: true, uniqueness: true
  validates :well_known_text, presence: true
end

app/controllers/api/application_controller.rb
# frozen_string_literal: true

class Api::ApplicationController < ActionController::API
  before_action :disable_cache

  delegate :t, to: I18n

  private

  def disable_cache
    expires_now
  end
end

app/controllers/api/v1/tickets_controller.rb
# frozen_string_literal: true

class Api::V1::TicketsController < Api::ApplicationController
  def create
    command = Api::V1::Tickets::CreateTicketCommand.call(json_data: params[:json_data])

    if command.ok?
      render json: { message: t('controllers.api_v1_tickets.create.success') }, status: :created
    else
      render json: { errors: command.errors }, status: :unprocessable_entity
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  rescue_from ActiveRecord::RecordNotFound, with: :resource_not_found

  private

  def resource_not_found(exception)
    @error = exception
    Rails.logger.error "ERROR: #{ exception }"
    render 'errors/not_found', status: :not_found
  end
end

app/controllers/tickets_controller.rb
# frozen_string_literal: true

class TicketsController < ApplicationController
  DEFAULT_PER_PAGE = 10

  def index
    @tickets = Ticket.order(id: :desc).page(params[:page]).per(DEFAULT_PER_PAGE)
  end

  def show
    @ticket = Ticket.find(params[:id])
    @excavator = @ticket.excavator

    return unless @excavator.nil?

    raise ActiveRecord::RecordNotFound, t('controllers.tickets.show.errors.excavator_not_found', id: params[:id])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/tickets_helper.rb
# frozen_string_literal: true

module TicketsHelper
  def wkt
    @ticket.well_known_text
  end

  def row_number(index)
    index + 1 + ((@tickets.current_page - 1) * @tickets.limit_value)
  end

  def paginate_tickets(tickets)
    paginate tickets,
             theme: 'bootstrap-5',
             pagination_class: 'pagination-sm flex-wrap justify-content-center',
             nav_class: 'd-inline-block'
  end

  def ticket_attr(attribute)
    Ticket.human_attribute_name(attribute)
  end

  def excavator_attr(attribute)
    Excavator.human_attribute_name(attribute)
  end
end

app/views/layouts/application.slim
doctype html
html
  head
    title GeospatialDataViewer
    meta(name='viewport', content='width=device-width, initial-scale=1')
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', "data-turbo-track": 'reload'
    = javascript_importmap_tags
    script src='https://unpkg.com/leaflet@1.9.4/dist/leaflet.js' integrity='sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo=' crossorigin=''

  body
    .container
      = yield

app/views/tickets/_excavator.slim
.card
  .card-header
    h3.card-title = t 'views.tickets.excavator.title'
  .card-body
    .row
      .col-md-12
        p
          strong = "#{ excavator_attr(:id) }: "
          = @excavator.id
        p
          strong = "#{ excavator_attr(:company_name) }: "
          = @excavator.company_name
        p
          strong = "#{ excavator_attr(:address) }: "
          = @excavator.address
        p
          strong = "#{ excavator_attr(:crew_on_site) }: "
          - if @excavator.crew_on_site
            span.text-success
              i.bi.bi-check2-circle
          - else
            span.text-danger
              i.bi.bi-x-circle

app/views/tickets/_map.slim
.card
  .card-header
    h3.card-title = t 'views.tickets.map.title'
  .card-body
    .row
      .col-md-12
        div id='map'

javascript:
  var map = L.map('map').setView(#{ wkt.centroid.coordinates }, 12);

  L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
    maxZoom: 18,
    attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>'
  }).addTo(map);

  var polygon = L.polygon([
    #{ wkt.coordinates }
  ]).addTo(map);

app/views/tickets/_ticket.slim
.card
  .card-header
    h3.card-title = t 'views.tickets.ticket.title'
  .card-body
    .row
      .col-md-6
        p
          strong = "#{ ticket_attr(:id) }: "
          = @ticket.id
        p
          strong = "#{ ticket_attr(:request_number) }: "
          = @ticket.request_number
        p
          strong = "#{ ticket_attr(:sequence_number) }: "
          = @ticket.sequence_number
        p
          strong = "#{ ticket_attr(:request_type) }: "
          = @ticket.request_type
      .col-md-6
        p
          strong = "#{ ticket_attr(:request_action) }: "
          = @ticket.request_action
        p
          strong = "#{ ticket_attr(:response_due_date_time) }: "
          = @ticket.response_due_date_time
        p
          strong = "#{ ticket_attr(:primary_service_area_code) }: "
          = @ticket.primary_service_area_code
        p
          strong = "#{ ticket_attr(:additional_service_area_codes) }: "
          = @ticket.additional_service_area_codes

app/views/tickets/index.slim
.row
  .col-md-12.text-center.pt-3
    h2= t 'views.tickets.index.title'

hr

.row
  .col-md-12.text-center
    table.table.table-bordered.table-sm.table-striped
      thead
        tr
          th= '№'
          th= ticket_attr(:id)
          th= ticket_attr(:request_number)
          th= ticket_attr(:request_type)
          th= ticket_attr(:request_action)
          th= ticket_attr(:response_due_date_time)
          th=

      tbody
        - @tickets.each_with_index do |ticket, i|
          tr
            td= row_number(i)
            td= ticket.id
            td= ticket.request_number
            td= ticket.request_type
            td= ticket.request_action
            td= ticket.response_due_date_time
            td= link_to ticket_path(ticket), class: 'btn btn-link' do
              span.text-secondary.bi.bi-eye

  = paginate_tickets @tickets

app/views/tickets/show.slim
.row
  .col-md-12.text-center.pt-3
    h2= t 'views.tickets.show.title'

hr

.row.mt-3
  .col-md-12
    = render 'ticket'

.row.mt-3
  .col-md-12
    = render 'excavator'

.row.mt-3
  .col-md-12
    = render 'map'

.row
  .col-md-12.mt-3.mb-3
    = link_to t('views.tickets.show.back'), root_path, class: 'btn btn-secondary'